[package]
name = "osu-beatmap-preview-py"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Python bindings for osu-beatmap-preview"
repository = "https://github.com/yaowan233/osu-beatmap-preview-py"

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
osu-beatmap-preview-core = { package = "osu-beatmap-preview", git = "https://github.com/2710165659/osu-beatmap-preview", rev = "6c74511499fe781c655b4ef68d3c7e978c9c4212" }
pyo3 = { version = "0.23", features = ["abi3-py310", "extension-module"] }
serde_json = "1"

[profile.release]
codegen-units = 1
lto = "thin"
strip = true

